# Generated by Django 4.0.5 on 2022-06-23 23:00

from django.db import migrations, models
import profiles.models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_profile_options_alter_profile_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='foto',
            field=models.ImageField(default='images/no-image-icon.png', null=True, upload_to=profiles.models.user_directory_path, verbose_name='Foto'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='sexo',
            field=models.CharField(choices=[(None, 'selecciona'), ('h', 'Hombre'), ('m', 'Mujer')], default=None, max_length=1, null=True, verbose_name='Sexo'),
        ),
    ]
