# Generated by Django 4.0.5 on 2022-06-20 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='suscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=64, verbose_name='Nombre')),
                ('email', models.EmailField(max_length=64, verbose_name='Correo electrónico')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': ('Suscriber',),
                'verbose_name_plural': 'Suscribers',
                'db_table': 'suscribers',
                'ordering': ['nombre'],
            },
        ),
    ]
