# Generated by Django 4.0.5 on 2022-06-20 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suscriber',
            name='email',
            field=models.EmailField(max_length=64, unique=True, verbose_name='Correo electrónico'),
        ),
    ]
