# Generated by Django 4.0.5 on 2022-06-25 21:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25, verbose_name='Título')),
                ('subtitle', models.CharField(max_length=25, verbose_name='subtítulo')),
                ('content', models.TextField(max_length=3000, verbose_name='Contenido')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateField(blank=True, null=True, verbose_name='Fecha de publicación')),
                ('foto', models.ImageField(default='images/no-image-icon.png', null=True, upload_to='posts', verbose_name='Foto')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
                'db_table': 'posts',
                'ordering': ['created_at'],
            },
        ),
        migrations.DeleteModel(
            name='BlogPost',
        ),
    ]
