# Generated by Django 4.0.5 on 2022-06-26 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_post_content'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['published_at'], 'verbose_name': 'Post', 'verbose_name_plural': 'Posts'},
        ),
    ]
