# Generated by Django 4.0.5 on 2022-06-26 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_comment_content_alter_comment_person_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(default='Null', max_length=1600),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='person_name',
            field=models.CharField(default='Null', max_length=255),
            preserve_default=False,
        ),
    ]
