# Generated by Django 4.0.5 on 2022-06-26 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_alter_comment_content_alter_comment_person_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(max_length=1600, verbose_name='Contenido'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='person_name',
            field=models.CharField(max_length=16, verbose_name='Tu nombre:'),
        ),
    ]
